all:
  children:
    mysql_cluster:
      children:
        mysql_primary:
          hosts:
            mysql-node1:
              ansible_host: 192.168.1.10           # 替换为你的第一台服务器IP
              ansible_port: 22                      # 替换为你的第一台服务器SSH端口
              ansible_user: root                    # SSH用户名
              ansible_ssh_pass: "your_password_1"   # 替换为你的第一台服务器SSH密码
              mysql_server_id: 1
              mysql_role: primary
        mysql_secondary:
          hosts:
            mysql-node2:
              ansible_host: 192.168.1.11           # 替换为你的第二台服务器IP
              ansible_port: 22                      # 替换为你的第二台服务器SSH端口
              ansible_user: root                    # SSH用户名
              ansible_ssh_pass: "your_password_2"   # 替换为你的第二台服务器SSH密码
              mysql_server_id: 2
              mysql_role: secondary
            mysql-node3:
              ansible_host: 192.168.1.12           # 替换为你的第三台服务器IP
              ansible_port: 22                      # 替换为你的第三台服务器SSH端口
              ansible_user: root                    # SSH用户名
              ansible_ssh_pass: "your_password_3"   # 替换为你的第三台服务器SSH密码
              mysql_server_id: 3
              mysql_role: secondary
    mysql_router:
      hosts:
        mysql-router1:
          ansible_host: 192.168.1.10               # Router部署在第一台服务器上
          ansible_port: 22                          # 替换为你的第一台服务器SSH端口
          ansible_user: root
          ansible_ssh_pass: "your_password_1"       # 第一台服务器的密码
  vars:
    # 全局SSH配置
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_python_interpreter: /usr/bin/python3 