# MySQL版本和下载配置
mysql_version: "8.0.42"
mysql_major_version: "8.0"

# MySQL用户和密码配置
mysql_root_password: "MyS3cur3P@ssw0rd!"
mysql_cluster_user: "clusteradmin"
mysql_cluster_password: "Clust3rP@ss!"
mysql_replication_user: "replicator"
mysql_replication_password: "R3pl1c@t0r!"

# MySQL集群配置
mysql_cluster_name: "prodCluster"
mysql_group_replication_group_name: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"

# MySQL端口配置
mysql_port: 3306
mysql_admin_port: 33062
mysql_group_replication_port: 33061

# MySQL数据目录
mysql_datadir: "/data/mysql"
mysql_logdir: "/var/log/mysql"
mysql_tmpdir: "/tmp"

# 硬件配置类型 - 针对8核32G优化
mysql_hardware_profile: "optimized_8c32g"

# MySQL配置参数 - 专为8核32G内存优化
mysql_config_profiles:
  optimized_8c32g:  # 8核32G优化配置
    # InnoDB缓冲池 - 占用20G内存，为连接预留空间
    innodb_buffer_pool_size: "20G"
    # InnoDB日志文件大小 - 缓冲池的15%
    innodb_log_file_size: "3G"
    # 连接数配置 - 4000连接，内存安全
    max_connections: 4000
    # 线程缓存 - CPU核心数的4倍
    thread_cache_size: 32
    # 表缓存 - 适配4K连接
    table_open_cache: 8000
    # 查询缓存大小
    query_cache_size: "256M"
    # 排序缓冲区
    sort_buffer_size: "2M"
    # 读缓冲区
    read_buffer_size: "1M"
    # 随机读缓冲区
    read_rnd_buffer_size: "2M"
    # 批量插入缓冲区
    bulk_insert_buffer_size: "64M"
    # 临时表大小
    tmp_table_size: "512M"
    max_heap_table_size: "512M"
    # InnoDB额外配置
    innodb_buffer_pool_instances: 8
    innodb_io_capacity: 2000
    innodb_io_capacity_max: 4000
    innodb_read_io_threads: 8
    innodb_write_io_threads: 8
    innodb_thread_concurrency: 16
    # 高并发优化参数
    back_log: 400                        # 连接队列，10%的max_connections
    thread_stack: 512K
    table_open_cache_instances: 8
    open_files_limit: 20000              # 连接数的5倍
    
# 当前配置（根据硬件配置文件选择）
mysql_innodb_buffer_pool_size: "{{ mysql_config_profiles[mysql_hardware_profile].innodb_buffer_pool_size }}"
mysql_innodb_log_file_size: "{{ mysql_config_profiles[mysql_hardware_profile].innodb_log_file_size }}"
mysql_max_connections: "{{ mysql_config_profiles[mysql_hardware_profile].max_connections }}"
mysql_thread_cache_size: "{{ mysql_config_profiles[mysql_hardware_profile].thread_cache_size }}"
mysql_table_open_cache: "{{ mysql_config_profiles[mysql_hardware_profile].table_open_cache }}"
mysql_query_cache_size: "{{ mysql_config_profiles[mysql_hardware_profile].query_cache_size }}"
mysql_sort_buffer_size: "{{ mysql_config_profiles[mysql_hardware_profile].sort_buffer_size }}"
mysql_read_buffer_size: "{{ mysql_config_profiles[mysql_hardware_profile].read_buffer_size }}"
mysql_read_rnd_buffer_size: "{{ mysql_config_profiles[mysql_hardware_profile].read_rnd_buffer_size }}"
mysql_bulk_insert_buffer_size: "{{ mysql_config_profiles[mysql_hardware_profile].bulk_insert_buffer_size }}"
mysql_tmp_table_size: "{{ mysql_config_profiles[mysql_hardware_profile].tmp_table_size }}"
mysql_max_heap_table_size: "{{ mysql_config_profiles[mysql_hardware_profile].max_heap_table_size }}"
mysql_innodb_buffer_pool_instances: "{{ mysql_config_profiles[mysql_hardware_profile].innodb_buffer_pool_instances }}"
mysql_innodb_io_capacity: "{{ mysql_config_profiles[mysql_hardware_profile].innodb_io_capacity }}"
mysql_innodb_io_capacity_max: "{{ mysql_config_profiles[mysql_hardware_profile].innodb_io_capacity_max }}"
mysql_innodb_read_io_threads: "{{ mysql_config_profiles[mysql_hardware_profile].innodb_read_io_threads }}"
mysql_innodb_write_io_threads: "{{ mysql_config_profiles[mysql_hardware_profile].innodb_write_io_threads }}"
mysql_innodb_thread_concurrency: "{{ mysql_config_profiles[mysql_hardware_profile].innodb_thread_concurrency }}"

# 系统配置
mysql_user: "mysql"
mysql_group: "mysql"

# 防火墙端口
firewall_ports:
  - "{{ mysql_port }}/tcp"
  - "{{ mysql_admin_port }}/tcp"
  - "{{ mysql_group_replication_port }}/tcp"

# MySQL Router配置 - 针对4核8G优化
mysql_router_port: 6446
mysql_router_admin_port: 8443

# 4核8G Router优化配置
mysql_router_4c8g_optimized:
  # 连接配置 - 保持3万连接能力
  max_connections: 30000
  max_connections_per_route: 15000
  connection_timeout: 30
  read_timeout: 30
  write_timeout: 30
  max_connect_errors: 100
  
  # CPU和内存优化 - 适配4核8G硬件
  router_threads: 6                     # 调整到6个线程（4核的1.5倍）
  io_threads: 4                         # I/O线程数
  connection_pool_size: 500             # 连接池大小
  memory_limit: "6GB"                   # 内存限制（为系统预留2GB）
  
  # 缓存配置
  metadata_cache_ttl: 300
  metadata_cache_refresh: 60
  
  # 路由策略
  routing_strategy_rw: "first-available"
  routing_strategy_ro: "round-robin"

# 架构检测
mysql_architecture_map:
  x86_64: "x86_64"
  aarch64: "aarch64"
  arm64: "aarch64"

# CentOS版本检测
centos_version_map:
  "7": "el7"
  "8": "el8"

# 内存使用分析（8核32G配置）
memory_analysis_8c32g:
  total_memory: "32GB"
  innodb_buffer_pool: "20GB"           # 62.5%
  connection_memory: "8GB"             # 4000 × 2MB
  system_memory: "4GB"                 # 12.5%
  safety_margin: "0GB"                # 刚好用完
  max_safe_connections: 4000
  
# Router内存使用分析（4核8G配置）
memory_analysis_4c8g_router:
  total_memory: "8GB"
  router_base_memory: "1.5GB"
  connection_memory: "0.5GB"          # 30000 × 16KB
  cache_memory: "1GB"
  buffer_memory: "1GB"
  system_memory: "2GB"
  total_used: "6GB"
  safety_margin: "2GB"                # 25%预留

# 性能预期
performance_expectations:
  mysql_cluster:
    total_backend_connections: 12000   # 3 × 4000
    estimated_qps: "150K-200K"        # 读多写少场景
    memory_efficiency: "100%"         # 充分利用32G内存
    
  router_cluster:
    total_frontend_connections: 60000  # 2 × 30000
    connection_reuse_ratio: "5:1"     # 60K前端 → 12K后端
    estimated_throughput: "300K QPS"  # Router层吞吐量
    cpu_efficiency: "75%"             # 4核使用率
    
  overall_system:
    scalability: "Enterprise Ready"
    high_availability: "99.9%+"
    operational_complexity: "Low"
    maintenance_window: "<30min" 